/homes/benjaminv/programs/miniconda/lib/python3.7/runpy.py:125: RuntimeWarning: 'gridmap.runner' found in sys.modules after import of package 'gridmap', but prior to execution of 'gridmap.runner'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-03-08 00:49:29,024 - __main__ - INFO - Appended /homes/benjaminv/Code/ferromtm/ferromtm/models to PYTHONPATH
2019-03-08 00:49:29,024 - __main__ - INFO - Starting heart beat
2019-03-08 00:49:29,034 - __main__ - INFO - Waiting 0 seconds before fetching input
2019-03-08 00:49:30,393 - __main__ - ERROR - Could not retrieve input for job 354981
Traceback (most recent call last):
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/gridmap/runner.py", line 204, in _run_job
    job = _send_zmq_msg(job_id, "fetch_input", None, address)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/gridmap/runner.py", line 87, in _send_zmq_msg
    msg = zloads(zsocket.recv())
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/gridmap/data.py", line 63, in zloads
    return pickle.loads(bz2.decompress(pickled_data))
  File "/homes/benjaminv/Code/ferromtm/ferromtm/models/run_rand.py", line 1, in <module>
    from coupled2D import *
  File "/homes/benjaminv/Code/ferromtm/ferromtm/models/coupled2D.py", line 12, in <module>
    from pytheas.homogenization import *
  File "/homes/benjaminv/Code/pytheas/pytheas/__init__.py", line 14, in <module>
    from .basefem import BaseFEM
  File "/homes/benjaminv/Code/pytheas/pytheas/basefem/__init__.py", line 18, in <module>
    from .basefem import *
  File "/homes/benjaminv/Code/pytheas/pytheas/basefem/basefem.py", line 22, in <module>
    from ..tools import femio
  File "/homes/benjaminv/Code/pytheas/pytheas/tools/femio.py", line 7, in <module>
    import meshio
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/meshio/__init__.py", line 33, in <module>
    print(pipdate.check(__name__, __version__), end="")
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/pipdate/main.py", line 105, in check
    _log_time(name, datetime.now())
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/pipdate/main.py", line 61, in _log_time
    d = json.load(handle)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
